require('dotenv').config();
const express=require('express'),cors=require('cors'),multer=require('multer'),path=require('path'),fs=require('fs'),bcrypt=require('bcryptjs'),{v4:uuid}=require('uuid'),{spawn}=require('child_process');
const db=require('./db');const {sign,auth}=require('./auth');const {PLANS,createSubscription}=require('./payments');
const app=express();const PORT=process.env.PORT||3000;const ROOT=__dirname,UPLOAD=path.join(ROOT,'uploads'),OUTPUT=path.join(ROOT,'outputs'),VOICES=path.join(ROOT,'voices');[UPLOAD,OUTPUT,VOICES].forEach(x=>fs.mkdirSync(x,{recursive:true}));
app.use(cors({origin:true}));app.use(express.json());app.use(express.static(path.join(ROOT,'..','frontend')));
const maxGB=Number(process.env.MAX_FILE_SIZE_GB||2);const storage=multer.diskStorage({destination:UPLOAD,filename:(req,file,cb)=>cb(null,uuid()+path.extname(file.originalname))});
const upload=multer({storage,limits:{fileSize:maxGB*1024*1024*1024}});
const jobs=new Map();const queue=[];let busy=false;
function userRow(id){return db.prepare('SELECT id,name,email,plan,subscription_status,subscription_id,created_at FROM users WHERE id=?').get(id)}
function quota(plan){return PLANS[plan]?.minutes||10}
function enqueue(id){queue.push(id);runQueue()}
function runQueue(){if(busy||!queue.length)return;const id=queue.shift(),j=jobs.get(id);if(!j){return runQueue()}busy=true;j.status='processing';j.stage='iniciando';const output=path.join(OUTPUT,id+'.mp4');j.outputPath=output;db.prepare('UPDATE jobs SET status=?,stage=?,output_path=? WHERE id=?').run(j.status,j.stage,output,id);
 const args=['pipeline.py','--input',j.inputPath,'--output',output,'--target-lang',j.targetLang,'--voice-mode',j.voiceMode];if(j.voicePath)args.push('--speaker-wav',j.voicePath);const py=spawn(process.env.PYTHON_BIN||'python3',[path.join(ROOT,'worker',...args)]);
 py.stdout.on('data',d=>d.toString().split('\n').filter(Boolean).forEach(line=>{if(line.startsWith('STAGE:'))j.stage=line.slice(6).trim();if(line.startsWith('PROGRESS:'))j.progress=Number(line.slice(9).trim());db.prepare('UPDATE jobs SET progress=?,stage=? WHERE id=?').run(j.progress,j.stage,id)}));let err='';py.stderr.on('data',d=>err+=d.toString());py.on('close',code=>{if(code===0){j.status='done';j.progress=100;j.stage='concluído';j.finishedAt=Date.now();db.prepare('UPDATE jobs SET status=?,progress=?,stage=?,finished_at=? WHERE id=?').run('done',100,j.stage,j.finishedAt,id)}else{j.status='error';j.error=err.slice(-3000);db.prepare('UPDATE jobs SET status=?,error=? WHERE id=?').run('error',j.error,id)}busy=false;runQueue()})}
app.get('/api/health',(req,res)=>res.json({ok:true,version:'2.0.0'}));
app.post('/api/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Nome, e-mail e senha (mínimo 6 caracteres) são obrigatórios.'});const exists=db.prepare('SELECT id FROM users WHERE email=?').get(email.toLowerCase());if(exists)return res.status(409).json({error:'Este e-mail já está cadastrado.'});const id=uuid();const hash=await bcrypt.hash(password,12);db.prepare('INSERT INTO users(id,name,email,password_hash,created_at) VALUES(?,?,?,?,?)').run(id,name.trim(),email.toLowerCase(),hash,Date.now());const u=userRow(id);res.json({token:sign(u),user:u})}catch(e){res.status(500).json({error:'Não foi possível criar a conta.'})}});
app.post('/api/login',async(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get((email||'').toLowerCase());if(!u||!(await bcrypt.compare(password||'',u.password_hash)))return res.status(401).json({error:'E-mail ou senha inválidos.'});res.json({token:sign(u),user:userRow(u.id)})});
app.get('/api/me',auth,(req,res)=>res.json({user:userRow(req.user.sub)}));
app.get('/api/plans',(req,res)=>res.json({plans:PLANS}));
app.post('/api/subscribe',auth,async(req,res)=>{try{const plan=req.body.plan;if(!['basic','pro'].includes(plan))return res.status(400).json({error:'Plano inválido.'});const u=userRow(req.user.sub);const result=await createSubscription(plan,u);db.prepare('INSERT INTO payments(id,user_id,plan,status,external_id,created_at) VALUES(?,?,?,?,?,?)').run(uuid(),u.id,plan,'pending',result.id,Date.now());res.json({url:result.init_point,id:result.id})}catch(e){res.status(400).json({error:e.message})}});
// Webhook simples: confirme o status consultando a API do Mercado Pago antes de liberar o plano.
app.post('/api/webhooks/mercadopago',async(req,res)=>{try{const id=req.body?.data?.id||req.body?.id;if(!id)return res.sendStatus(200);if(!process.env.MP_ACCESS_TOKEN)return res.sendStatus(200);const r=await fetch('https://api.mercadopago.com/preapproval/'+id,{headers:{Authorization:'Bearer '+process.env.MP_ACCESS_TOKEN}});if(!r.ok)return res.sendStatus(200);const sub=await r.json();const p=db.prepare('SELECT * FROM payments WHERE external_id=?').get(String(id));if(p){const plan=p.plan;db.prepare('UPDATE payments SET status=? WHERE external_id=?').run(sub.status,String(id));if(sub.status==='authorized'||sub.status==='active')db.prepare('UPDATE users SET plan=?,subscription_status=?,subscription_id=? WHERE id=?').run(plan,'active',String(id),p.user_id);else if(['cancelled','paused'].includes(sub.status))db.prepare('UPDATE users SET plan=?,subscription_status=? WHERE id=?').run('free',sub.status,p.user_id)}}catch(e){}res.sendStatus(200)});
app.post('/api/dublar',auth,upload.fields([{name:'video',maxCount:1},{name:'voiceSample',maxCount:1}],), (req,res)=>{try{const video=req.files?.video?.[0];if(!video)return res.status(400).json({error:'Envie um vídeo.'});const targetLang=req.body.targetLang||'pt';const voiceMode=req.body.voiceMode==='clone'?'clone':'standard';const u=userRow(req.user.sub);if(voiceMode==='clone'&&!PLANS[u.plan].voices)return res.status(403).json({error:'Clonagem de voz disponível a partir do plano Creator.'});const voice=req.files?.voiceSample?.[0];if(voiceMode==='clone'&&!voice)return res.status(400).json({error:'Envie uma amostra de voz para clonagem.'});const id=uuid(),voicePath=voice?voice.path:null;const job={id,userId:u.id,inputPath:video.path,voicePath,originalName:video.originalname,targetLang,voiceMode,status:'queued',progress:0,stage:'na fila',createdAt:Date.now()};jobs.set(id,job);db.prepare('INSERT INTO jobs(id,user_id,original_name,status,progress,stage,target_lang,voice_mode,voice_path,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,u.id,video.originalname,'queued',0,'na fila',targetLang,voiceMode,voicePath,Date.now());enqueue(id);res.json({jobId:id,status:'queued'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/status/:id',auth,(req,res)=>{const j=jobs.get(req.params.id)||db.prepare('SELECT * FROM jobs WHERE id=?').get(req.params.id);if(!j||j.userId&&j.userId!==req.user.sub||j.user_id&&j.user_id!==req.user.sub)return res.status(404).json({error:'Job não encontrado.'});res.json({id:j.id,status:j.status,progress:j.progress,stage:j.stage,error:j.error||null,downloadUrl:j.status==='done'?'/api/download/'+j.id:null})});
app.get('/api/meus-videos',auth,(req,res)=>{const rows=db.prepare('SELECT id,original_name,status,progress,stage,target_lang,voice_mode,created_at,finished_at FROM jobs WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(req.user.sub);res.json({videos:rows})});
app.get('/api/download/:id',auth,(req,res)=>{const j=db.prepare('SELECT * FROM jobs WHERE id=? AND user_id=?').get(req.params.id,req.user.sub);if(!j||j.status!=='done'||!j.output_path||!fs.existsSync(j.output_path))return res.status(404).json({error:'Arquivo não disponível.'});res.download(j.output_path,'video-dublado.mp4')});
app.listen(PORT,()=>console.log(`Dublagem AI v2 rodando em http://localhost:${PORT}`));
